[2025-10-08T23:40:03.206+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-08T23:40:03.226+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: orchestrator_bronze_silver_refined.upload_to_bronze manual__2025-10-08T23:38:14+00:00 [queued]>
[2025-10-08T23:40:03.232+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: orchestrator_bronze_silver_refined.upload_to_bronze manual__2025-10-08T23:38:14+00:00 [queued]>
[2025-10-08T23:40:03.232+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-10-08T23:40:03.240+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): upload_to_bronze> on 2025-10-08 23:38:14+00:00
[2025-10-08T23:40:03.249+0000] {standard_task_runner.py:64} INFO - Started process 1468 to run task
[2025-10-08T23:40:03.251+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'orchestrator_bronze_silver_refined', 'upload_to_bronze', 'manual__2025-10-08T23:38:14+00:00', '--job-id', '44', '--raw', '--subdir', 'DAGS_FOLDER/dag_orchestrator_pipeline.py', '--cfg-path', '/tmp/tmp6rsrsgs1']
[2025-10-08T23:40:03.253+0000] {standard_task_runner.py:91} INFO - Job 44: Subtask upload_to_bronze
[2025-10-08T23:40:03.287+0000] {task_command.py:426} INFO - Running <TaskInstance: orchestrator_bronze_silver_refined.upload_to_bronze manual__2025-10-08T23:38:14+00:00 [running]> on host c70502277107
[2025-10-08T23:40:03.349+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Fia' AIRFLOW_CTX_DAG_ID='orchestrator_bronze_silver_refined' AIRFLOW_CTX_TASK_ID='upload_to_bronze' AIRFLOW_CTX_EXECUTION_DATE='2025-10-08T23:38:14+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-08T23:38:14+00:00'
[2025-10-08T23:40:03.349+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-08T23:40:03.381+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-08T23:40:03.389+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_orchestrator_pipeline.py", line 35, in upload_to_bronze
    raise AirflowException(f"Local CSV not found: {LOCAL_CSV}")
airflow.exceptions.AirflowException: Local CSV not found: /opt/***/dags/../../content/files/netflix_titles.csv
[2025-10-08T23:40:03.391+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=orchestrator_bronze_silver_refined, task_id=upload_to_bronze, run_id=manual__2025-10-08T23:38:14+00:00, execution_date=20251008T233814, start_date=20251008T234003, end_date=20251008T234003
[2025-10-08T23:40:03.402+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 44 for task upload_to_bronze (Local CSV not found: /opt/***/dags/../../content/files/netflix_titles.csv; 1468)
[2025-10-08T23:40:03.425+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-10-08T23:40:03.442+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-08T23:40:03.445+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
