[2025-10-08T23:44:31.982+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-08T23:44:32.038+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: orchestrator_bronze_silver_refined.upload_to_bronze manual__2025-10-08T23:44:30+00:00 [queued]>
[2025-10-08T23:44:32.053+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: orchestrator_bronze_silver_refined.upload_to_bronze manual__2025-10-08T23:44:30+00:00 [queued]>
[2025-10-08T23:44:32.055+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-10-08T23:44:32.081+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): upload_to_bronze> on 2025-10-08 23:44:30+00:00
[2025-10-08T23:44:32.110+0000] {standard_task_runner.py:64} INFO - Started process 257 to run task
[2025-10-08T23:44:32.115+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'orchestrator_bronze_silver_refined', 'upload_to_bronze', 'manual__2025-10-08T23:44:30+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/dag_orchestrator_pipeline.py', '--cfg-path', '/tmp/tmp4j9zzfl6']
[2025-10-08T23:44:32.117+0000] {standard_task_runner.py:91} INFO - Job 50: Subtask upload_to_bronze
[2025-10-08T23:44:32.205+0000] {task_command.py:426} INFO - Running <TaskInstance: orchestrator_bronze_silver_refined.upload_to_bronze manual__2025-10-08T23:44:30+00:00 [running]> on host 651334a32e37
[2025-10-08T23:44:32.362+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Fia' AIRFLOW_CTX_DAG_ID='orchestrator_bronze_silver_refined' AIRFLOW_CTX_TASK_ID='upload_to_bronze' AIRFLOW_CTX_EXECUTION_DATE='2025-10-08T23:44:30+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-08T23:44:30+00:00'
[2025-10-08T23:44:32.362+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-08T23:44:32.399+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-08T23:44:32.416+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_orchestrator_pipeline.py", line 35, in upload_to_bronze
    raise AirflowException(f"Local CSV not found: {LOCAL_CSV}")
airflow.exceptions.AirflowException: Local CSV not found: /opt/***/dags/../../content/files/netflix_titles.csv
[2025-10-08T23:44:32.424+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=orchestrator_bronze_silver_refined, task_id=upload_to_bronze, run_id=manual__2025-10-08T23:44:30+00:00, execution_date=20251008T234430, start_date=20251008T234432, end_date=20251008T234432
[2025-10-08T23:44:32.448+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 50 for task upload_to_bronze (Local CSV not found: /opt/***/dags/../../content/files/netflix_titles.csv; 257)
[2025-10-08T23:44:32.501+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-10-08T23:44:32.548+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-08T23:44:32.557+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
